name: Java Maven CI

on:
  push:
    branches:
      - main  # Change this to your desired branch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn -B clean package --file pom.xml

      - name: Test with Maven
        run: mvn test --file pom.xml
