name: tests

on:
  push:
    branches:
      - master  # Change this to your desired branch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '22'

      - name: Build with Maven
        run: mvn -B clean package --file pom.xml

      - name: Test with Maven and Generate Coverage
        run: mvn clean test jacoco:report --file pom.xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./target/site/jacoco/jacoco.xml
